<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spatial analysis of public health data - 2&nbsp; Raster and reproducibility</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_point_patterns.html" rel="next">
<link href="./01_geographic_data.html" rel="prev">
<link href="./assets/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./general_images/casa_logo.jpg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Spatial analysis of public health data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
            <div class="quarto-navbar-tools">
    <a href="https://github.com/andrewmaclachlan/digital-urban-hyderabad" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02_raster_reproducibility.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Raster and reproducibility</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software installation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_geographic_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Geographic information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_raster_reproducibility.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Raster and reproducibility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_point_patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Point patterns and autocorrelation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_spatial_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes"><span class="header-section-number">2.1</span> Learning outcomes</a></li>
  <li><a href="#rmarkdown-quarto" id="toc-rmarkdown-quarto" class="nav-link" data-scroll-target="#rmarkdown-quarto"><span class="header-section-number">2.2</span> RMarkdown / Quarto</a></li>
  <li><a href="#intro" id="toc-intro" class="nav-link" data-scroll-target="#intro"><span class="header-section-number">2.3</span> Intro</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2.4</span> Data</a>
  <ul class="collapse">
  <li><a href="#data-loading" id="toc-data-loading" class="nav-link" data-scroll-target="#data-loading"><span class="header-section-number">2.4.1</span> Data loading</a></li>
  <li><a href="#projection" id="toc-projection" class="nav-link" data-scroll-target="#projection"><span class="header-section-number">2.4.2</span> Projection</a></li>
  <li><a href="#reprojecting" id="toc-reprojecting" class="nav-link" data-scroll-target="#reprojecting"><span class="header-section-number">2.4.3</span> Reprojecting</a></li>
  <li><a href="#data-joining" id="toc-data-joining" class="nav-link" data-scroll-target="#data-joining"><span class="header-section-number">2.4.4</span> Data joining</a></li>
  <li><a href="#malaria-per-lga" id="toc-malaria-per-lga" class="nav-link" data-scroll-target="#malaria-per-lga"><span class="header-section-number">2.4.5</span> Malaria per LGA</a></li>
  <li><a href="#final-dataset" id="toc-final-dataset" class="nav-link" data-scroll-target="#final-dataset"><span class="header-section-number">2.4.6</span> Final dataset</a></li>
  <li><a href="#calculations" id="toc-calculations" class="nav-link" data-scroll-target="#calculations"><span class="header-section-number">2.4.7</span> Calculations</a></li>
  </ul></li>
  <li><a href="#git-github-rmarkdown" id="toc-git-github-rmarkdown" class="nav-link" data-scroll-target="#git-github-rmarkdown"><span class="header-section-number">2.5</span> Git, GitHub, RMarkdown</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">2.5.1</span> Setup</a></li>
  <li><a href="#using-rstudio-with-git" id="toc-using-rstudio-with-git" class="nav-link" data-scroll-target="#using-rstudio-with-git"><span class="header-section-number">2.5.2</span> Using RStudio with Git</a></li>
  <li><a href="#way-1---starting-fresh" id="toc-way-1---starting-fresh" class="nav-link" data-scroll-target="#way-1---starting-fresh"><span class="header-section-number">2.5.3</span> Way 1 - starting fresh</a></li>
  <li><a href="#way-2---if-have-an-existing-project" id="toc-way-2---if-have-an-existing-project" class="nav-link" data-scroll-target="#way-2---if-have-an-existing-project"><span class="header-section-number">2.5.4</span> Way 2 - If have an existing project</a></li>
  <li><a href="#commiting-to-git" id="toc-commiting-to-git" class="nav-link" data-scroll-target="#commiting-to-git"><span class="header-section-number">2.5.5</span> Commiting to Git</a></li>
  <li><a href="#push-to-github" id="toc-push-to-github" class="nav-link" data-scroll-target="#push-to-github"><span class="header-section-number">2.5.6</span> Push to Github</a></li>
  <li><a href="#pull-from-github" id="toc-pull-from-github" class="nav-link" data-scroll-target="#pull-from-github"><span class="header-section-number">2.5.7</span> Pull from GitHub</a></li>
  <li><a href="#forking" id="toc-forking" class="nav-link" data-scroll-target="#forking"><span class="header-section-number">2.5.8</span> Forking</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/andrewmaclachlan/digital-urban-hyderabad/edit/main/02_raster_reproducibility.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/andrewmaclachlan/digital-urban-hyderabad/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Raster and reproducibility</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reading</strong></p>
<ul>
<li><p><a href="https://rmd4sci.njtierney.com/why-rmarkdown.html#reproducibility-is-a-problem">Chapter 2 “Why RMarkdown”</a> from RMarkdown for Scientists by Tierney (2020).</p></li>
<li><p><a href="https://www.pnas.org/doi/10.1073/pnas.2015759118?cookieSet=1">Replication across space and time must be weak in the social and environmental sciences</a> by Goodchild and Wenwen (2020).</p></li>
</ul>
<p><strong>Watching</strong></p>
<ul>
<li><a href="https://www.youtube.com/watch?v=eWxxfttcMts">Git for Humas by Alice Bartlett from UX Brighton</a></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The homework task is presented at the bottom of this practical.</p>
</div>
</div>
<section id="learning-outcomes" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="learning-outcomes"><span class="header-section-number">2.1</span> Learning outcomes</h2>
<p>By the end of this practical you should be able to:</p>
<ol type="1">
<li>Load, manipulate and interpret raster layers</li>
<li>Explain the use of and differences between Git and GitHub</li>
<li>Create reproducible and open R code</li>
<li>Produce RMarkdown documents that explain code and analysis</li>
</ol>
</section>
<section id="rmarkdown-quarto" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="rmarkdown-quarto"><span class="header-section-number">2.2</span> RMarkdown / Quarto</h2>
<p>Before we start the practical content we should now be moving to a type of markdown file as opposed to R scripts. This could be either a Quarto file or R Markdown. Both let you can show code, explanations and results within the same document.</p>
<p>Often it could be very hard to reproduce results owing to a lack of information in the methodology / user guides or walk through not matching up with the latest version of software. Think back to a time where you had to use software and consult a massive user guide in how to use it. Markdown is a big improvement as it puts all of the information in the same document, which can then be converted into a range of different formats — html for webpages, word documents, PDFs, blogs, books — virtually everything!</p>
<p>RMarkdown is dependent on R, however the recent development of Quarto has removed the reliance on R being multilingual with R, Python, Javascript and Julia. Quarto is separate software but (i think) is now installed by defaulted with R.</p>
<p>In your Rproject go, File &gt; New File &gt; select R Markdown or Quarto.</p>
<p>In RMarkdown you will see a “knit” option at the bar just above your code. In Quarto this will be “render”. These will run all code in the entire document and allow us to export our code to other formats - such as html or pdf.</p>
<p>You must put your code in a code chunk and these can be added with C+ in the top tool bar. We can control code chunks in different ways….</p>
<ul>
<li><code>echo=FALSE</code> - code does not appear in the final rendered document but the output does</li>
<li><code>message=FALSE</code> - messages don’t appear</li>
<li><code>warning=FALSE</code> - warnings don’t appear</li>
<li><code>eval=FALSE</code> - the code in that chunk does not run.</li>
</ul>
<p>Heading levels are denoted by <code>#</code></p>
<p>e.g.&nbsp;<code>#</code> = level 1, <code>##</code> level 2 and so on. In the bottom left of your code you will see an orange <code>#</code> which will let you navigate between your headings.</p>
<p>Start today with an RMarkdown or Quarto file. If you select the latter you can also make use of the visual editor which will make the Quarto file look like a word processor (top left of the document).</p>
</section>
<section id="intro" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="intro"><span class="header-section-number">2.3</span> Intro</h2>
<p>Today we are going to take some pixel level data (raster data) &gt; summarise it per polygon (e.g.&nbsp;country or district) &gt; share out code with the world on GitHub.</p>
</section>
<section id="data" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="data"><span class="header-section-number">2.4</span> Data</h2>
<p>We will use data from the Malaria Atlas project - specifically count of deaths from Plasmodium falciparum (malaria). We’ll also get some boundary data from the <a href="https://data.humdata.org/">Humanitarian Data Exchange</a>. Note, we could use <a href="https://gadm.org/">the Database of Global Administrative Areas - (GADM)</a>, however we would need to do some advanced data wrangling when joining the non-spatial data to the spatial data.</p>
<p>I will use Nigeria as an example, but feel free to select another country.</p>
<ul>
<li><a href="https://data.humdata.org/dataset/cod-ab-nga?force_layout=desktop">Nigeria Local Govenrment Area boundaries bondaries</a>. <strong>Note</strong>, this is the second option - <strong>not</strong> the file that includes <code>.gbd</code></li>
<li><a href="https://data.malariaatlas.org/maps?layers=Malaria:202206_Global_Pf_Mortality_Rate">count of deaths from Plasmodium falciparum (malaria)</a>. I have downloaded the whole world, but you can also select just the country.</li>
<li><a href="https://data.humdata.org/dataset/cod-ps-nga?">2020 population data</a>, in order to normalise our data.</li>
</ul>
<section id="data-loading" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="data-loading"><span class="header-section-number">2.4.1</span> Data loading</h3>
<p>Load in the population data. We will need to join this data to a spatial layer later on, so check it for a unique identifier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"prac2_data/nga_admpop_adm2_2020.csv"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>(.)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># check the type of column</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Datatypelist <span class="ot">&lt;-</span> population <span class="sc">%&gt;%</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(class) <span class="sc">%&gt;%</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to=</span><span class="st">"All_variables"</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to=</span><span class="st">"Variable_class"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>Datatypelist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 78 × 2
   All_variables Variable_class
   &lt;chr&gt;         &lt;chr&gt;         
 1 adm0_name     character     
 2 adm0_pcode    character     
 3 adm1_name     character     
 4 adm1_pcode    character     
 5 adm2_name     character     
 6 adm2_pcode    character     
 7 f_tl          numeric       
 8 m_tl          numeric       
 9 t_tl          numeric       
10 f_00_04       numeric       
# … with 68 more rows</code></pre>
</div>
</div>
<p>Raster packages in R have and are still evolving rapidly. In 2023 some key packages will retired like <code>maptools</code>, <code>rgdal</code> and <code>rgeos</code> as their maintainer, Roger Bivand retired. The old <code>raster</code> used <code>sp</code> objects (the precursor to <code>sf</code>) for vector data and also the <code>rgdal</code> package - the Geospatial Data Abstraction Library (GDAL) for reading, writing and converting between spatial formats.</p>
<p>The <code>terra</code> package (2020) is somewhat similar to <code>raster</code>, however the retiring packages are only needed by <code>raster</code>, with the <code>terra</code> package replacing <code>raster</code>. <code>Terra</code> is much faster than raster as datasets that can’t be loaded into RAM are stored on disc and when loaded doesn’t read the values. Then when computations occur the do so in chunks. <code>terra</code> is very well documented and the functions are similar to <code>raster</code> - https://rspatial.org/terra/pkg/index.html</p>
<p>Load in the raster layer for 2020</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>malaria <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"prac2_data/202206_Global_Pf_Mortality_Count_2000/202206_Global_Pf_Mortality_Count_2020.tif"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check the raster info</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>malaria</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
dimensions  : 3480, 8640, 1  (nrow, ncol, nlyr)
resolution  : 0.04166667, 0.04166667  (x, y)
extent      : -180, 180, -60, 85  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : 202206_Global_Pf_Mortality_Count_2020.tif 
name        : 202206_Global_Pf_Mortality_Count_2020 
min value   :                                0.0000 
max value   :                              481.9917 </code></pre>
</div>
</div>
<p>We are going to use local government areas. According to Wikipedia, in Nigeria:</p>
<blockquote class="blockquote">
<p>The federal government’s role is mostly limited to coordinating the affairs of the university teaching hospitals, Federal Medical Centres (tertiary healthcare) while the state government manages the various general hospitals (secondary healthcare) and the local government focuses on dispensaries (primary healthcare),[4] which are regulated by the federal government through the NPHCDA.</p>
</blockquote>
<p>Despite this let’s calculate which local government area has the most cases…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>LGA <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"prac2_data/nga_adm_osgof_20190417/nga_admbnda_adm2_osgof_20190417.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `nga_admbnda_adm2_osgof_20190417' from data source 
  `C:\Users\Andy\OneDrive - University College London\Teaching\Guest\Oxford_24\Spatial analysis of public health data\prac2_data\nga_adm_osgof_20190417\nga_admbnda_adm2_osgof_20190417.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 774 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>But before we do…</p>
</section>
<section id="projection" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="projection"><span class="header-section-number">2.4.2</span> Projection</h3>
<p>Whilst yesterday we saw the theory of coordinate reference systems we didn’t actually change any!</p>
<p>The coordinates are stored in the geometry column of your sf object contain the information to enable points, lines or polygons to be drawn on the screen. Rasters are similar but contain the points of the bottom left pixel.</p>
<p>You can see in our cases we have:</p>
<ul>
<li><p>a SpatRaster with dimensions, extent and coord ref of lon/lat WGS 84 (EPSG:4326)</p></li>
<li><p>a multipolygon - every point within the polygon will have coordinates that are in a certain reference system, here Geodetic CRS: WGS 84. The geodetic means geographic, if it was a projected coordinate reference system it would say projected CRS</p></li>
</ul>
<p>We need some more information on projections before we can progress….</p>
<section id="wgs84" class="level4" data-number="2.4.2.1">
<h4 data-number="2.4.2.1" class="anchored" data-anchor-id="wgs84"><span class="header-section-number">2.4.2.1</span> WGS84</h4>
<p>The World Geodetic System 84 (WGS84 - last revised in 1984) is one of the most common global projection systems, used in nearly all GPS devices. However there are many versions of WGS84, some geographic and some projected coordinate reference systems.</p>
<p><strong>3D globe</strong></p>
<ul>
<li>GPS devices and point data sets often use the Geographic version (EPSG code 4326), <strong>usually referred to just as WGS84</strong></li>
<li>Google Earth uses the Geographic version as it is a 3D globe (EPSG code 4326)</li>
</ul>
<div class="infobox tip">
<p>In GIS if you add a layer that is 3D (e.g.&nbsp;in WGS84) it will map it on the 2D screen! But how? It takes the latitude and longitude values and maps them as planar coordinates. This means it linearly maps 3D points to a 2D plane….some people might refer to this as “unprojected” but i would say that it has a geographic coordinate reference system.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/150px-Axonometric_projection.svg.png" class="img-fluid figure-img" style="width:30.0%"></p>
<figcaption class="figure-caption">Planar projections. Source: <a href="https://en.wikipedia.org/wiki/Planar_projection">Wikipedia (2023)</a></figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Flat</strong></p>
<ul>
<li>Google Maps / Carto / Bing / Open street map use Web Mercator, Google Web Mercator, Spherical Mercator, WGS 84 Web Mercator or <strong>WGS 84/Pseudo-Mercator</strong> which is a projected coordinate reference system (EPSG code 3857). It is a variant of the Mercator map projection.</li>
<li>The WGS 1984 world Mercator projection is a projected coordinate reference system following the Mercator map transformation (EPSG code 3395)</li>
</ul>
<p>The projected versions will have units of meters and the geographic versions units of degrees.</p>
<p>In the rare occasion some data was collected in a Geographic coordinate reference system other than WGS84, you might find that the points / polygons won’t line up with data in WGS84. This is because different Geographic coordinate reference systems use different ellipsoids (shape / size of Earth) and/or datums (the origin point (0,0), typically they use Earth’s centre of gravity). To make them match you need to transform a dataset. That said QGIS will project ‘on the fly’ meaning if you add layers with a different CRS it will make them appear the same on the screen (changing the projection live or ‘on the fly’). It won’t change the CRS of the data itself though, you have to do that manually.</p>
<p>An example of another Geographic coordinate reference systems is the North American 1983 Datum (NAD83) that uses a different ellipsoid (longer by 0.21mm compared to WGS84), it also just has reference points on the North America plate (that moves 1-2cm a year), WGS84 has them all over the world.</p>
<p>This same logic applies for projected coordinate references systems that could be different, as they use a different origin and the projected coordinate reference system still contains the geographic one, the projected part tells the computer how to draw the shape.</p>
</section>
<section id="proj4" class="level4" data-number="2.4.2.2">
<h4 data-number="2.4.2.2" class="anchored" data-anchor-id="proj4"><span class="header-section-number">2.4.2.2</span> Proj4</h4>
<p>Whilst we were able to identify the CRS of our layer using <code>print</code> another alternative is to find the <code>proj4</code> string. A <code>proj4</code> string is meant to be a compact way of identifying a coordinate reference system. Let’s extract ours…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(LGA)<span class="sc">$</span>proj4string</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "+proj=longlat +datum=WGS84 +no_defs"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>“Well that’s clear as mud!” I hear you cry! Yes, not obvious is it!</p>
</blockquote>
<p>The proj4-string basically tells the computer where on the earth to locate the coordinates that make up the geometries in your file and what distortions to apply (i.e.&nbsp;if to flatten it out completely etc.) It’s composed of a list of parameters separated by a <code>+</code>. Here are projection <code>proj</code> uses latitude and longitude (so it’s a geographic not projected CRS). The <code>datum</code> is WGS84 that uses Earth’s centre mass as the coordinate origin (0,0).</p>
<p>The <a href="https://mgimond.github.io/Spatial/coordinate-systems-in-r.html#understanding-the-proj4-coordinate-syntax">Coordiante systems in R chapter by Gimond (2019)</a> provides much more information on Proj4. However, i’d advise trying to use EPSG codes, which we come onto next.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sometimes you can download data from the web and it doesn’t have a CRS. If any boundary data you download does not have a coordinate reference system attached to it (NA is displayed in the coord. ref section), this is not a huge problem — it can be added afterwards by adding the proj4string to the file or just assigning an EPSG code.</p>
</div>
</div>
<p>To find the proj4-strings for a whole range of different geographic projections, use the search facility at [spatial reference] (http://spatialreference.org/) or [epsg.io] (http://epsg.io/.)</p>
</section>
<section id="epsg" class="level4" data-number="2.4.2.3">
<h4 data-number="2.4.2.3" class="anchored" data-anchor-id="epsg"><span class="header-section-number">2.4.2.3</span> EPSG</h4>
<p>Now, if you can store a whole proj4-string in your mind, you must be some kind of savant (why are you doing this course? you could make your fortune as a card-counting poker player or something!). The rest of us need something a little bit more easy to remember and for coordinate reference systems, the saviour is the European Petroleum Survey Group (EPSG) — (naturally!). Now managed and maintained by the <a href="http://www.epsg.org/">International Association of Oil and Gas producers</a> — EPSG codes are short numbers represent all coordinate reference systems in the world and link directly to proj4 strings. We saw these last week in the [Making some maps] section.</p>
<p>The EPSG code for the WGS84 World Geodetic System (usually the default CRS for most spatial data) is 4326 — http://epsg.io/4326</p>
<ol type="1">
<li>If our data didn’t have a spatial reference system, we could have just set it using <code>st_set_crs()</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>LGA <span class="ot">&lt;-</span> LGA <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_crs</span>(., <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Normally</strong> if a layer has a missing CRS, it’s WGS84. But check for any metadata that might list it.</p>
</section>
</section>
<section id="reprojecting" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="reprojecting"><span class="header-section-number">2.4.3</span> Reprojecting</h3>
<p>Reprojecting your data is something that you might have to (or want to) do, on occasion. Why? Well, one example might be if you want to measure the distance of a line object, or the distance between two polygons. This can be done far more easily in a projected coordinate system (where the units are measured in metres) than it can a geographic coordinate system such as WGS84 (where the units are degrees). It is good practice to select a local coordiante reference system to undertake your analysis in.</p>
<p><strong>However</strong> for generating online maps in packages like <code>leaflet</code>, your data will need to be in WGS84, rather than a projected (flat) reference system .</p>
<p>In our case the data has been provided in WGS84. Searching <a href="https://epsg.io/?q=Nigeria">epsg.io</a> gives us a variety of options - we are looking for a CRS in meters.</p>
<p>Before we reproject our data we should clip (cookie cutter) out our study area.</p>
<p><strong>Note</strong> our data must be in the same CRS when we do spatial operations..</p>
<p>Here:</p>
<ul>
<li><p>Cropping, crops the raster to the extent (typically a sqaure around the vector data)</p></li>
<li><p>Masking acts like a cookie cutter.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>malaria_nga <span class="ot">&lt;-</span> malaria <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">crop</span>(., LGA)<span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">mask</span>(., LGA)<span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">project</span>(., <span class="st">"EPSG:26393"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s re-project our vector data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>LGA_nga <span class="ot">&lt;-</span> LGA <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(., <span class="dv">26393</span>)<span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clean_names</span>(.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-joining" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4" class="anchored" data-anchor-id="data-joining"><span class="header-section-number">2.4.4</span> Data joining</h3>
<p>Join our population data to our vector data using the unique identifier in each of the datasets then select the columns we want to keep for this analysis…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>joined_data <span class="ot">&lt;-</span> LGA_nga <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>            population,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"adm2_pcode"</span> <span class="ot">=</span> <span class="st">"adm2_pcode"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(adm2_pcode, adm2_en, t_tl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="malaria-per-lga" class="level3" data-number="2.4.5">
<h3 data-number="2.4.5" class="anchored" data-anchor-id="malaria-per-lga"><span class="header-section-number">2.4.5</span> Malaria per LGA</h3>
<p>To extract the raster in each polygon <code>terra::extract()</code> will identify the cells that have a centroid (central point) within each polygon. I have used the argument <code>fun=sum()</code> which will then sum all of the cells within each polygon. <strong>Note</strong> the output length is 774 - the same as our sf polygon data. If we left this argument out it would return all of the cells and the ID’s would be replicated (e.g.&nbsp;the first four cells have the ID of 1 and are within the first polygon). The length of the data frame increases to around 43,000. We could still work out the sum per LGA by using <code>group_by()</code> and <code>summarise()</code> like we say yesterday.</p>
<p>This process will return a data frame where the ID reflects the row of the sf object (e.g.&nbsp;ID 1 is the top row of the sf polygon data). For more information of extracting raster data see the book <a href="https://tmieno2.github.io/R-as-GIS-for-Economists/extracting-values-from-raster-layers-for-vector-data.html">the section on rasters in R as GIS for Economists</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>LGA_pop_extract <span class="ot">&lt;-</span> malaria_nga <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">extract</span>(., joined_data, <span class="at">fun=</span>sum)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(LGA_pop_extract)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID X202206_Global_Pf_Mortality_Count_2020
1  1                               81.27723
2  2                              175.56953
3  3                               77.09993
4  4                              459.19845
5  5                               72.54519
6  6                              200.91585</code></pre>
</div>
</div>
</section>
<section id="final-dataset" class="level3" data-number="2.4.6">
<h3 data-number="2.4.6" class="anchored" data-anchor-id="final-dataset"><span class="header-section-number">2.4.6</span> Final dataset</h3>
<p>Add a unique ID to our joined data (the polygons with the population) then left join again with our malaria counts per</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>joined_data <span class="ot">&lt;-</span> joined_data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id :=</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(.)))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>joined_data_malaria <span class="ot">&lt;-</span> joined_data <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., LGA_pop_extract,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"id"</span> <span class="ot">=</span> <span class="st">"ID"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>(.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we have a spatial data set with the total population and malaria count for each LGA.</p>
</section>
<section id="calculations" class="level3" data-number="2.4.7">
<h3 data-number="2.4.7" class="anchored" data-anchor-id="calculations"><span class="header-section-number">2.4.7</span> Calculations</h3>
<p>Calculate the rate of malaria deaths per 100,000 of each LGA…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>joined_data_malaria <span class="ot">&lt;-</span> joined_data_malaria <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">death_rate_100_000 =</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>           (x202206_global_pf_mortality_count_2020<span class="sc">/</span>t_tl)<span class="sc">*</span><span class="dv">100000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Do not make a map yet! that forms part of the homework task…</p>
</section>
</section>
<section id="git-github-rmarkdown" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="git-github-rmarkdown"><span class="header-section-number">2.5</span> Git, GitHub, RMarkdown</h2>
<p>Here you will learn how to produce work that is open, reproducible, share able and portable using RStudio, RMarkdown, Git and GitHub. As more and more researchers and organisations publish associated code with their manuscripts or documents it’s very important to become adept at using these tools.</p>
<p>The tools you will use are:</p>
<ul>
<li><p>RStudio is a graphical user interface (that you should already be familiar with) — it contains a number of features which make it excellent for authoring reproducible and open geographic data science work.</p></li>
<li><p>RMarkdown is a version of the Markdown markup language which enables plain text to be formatted to contain links to data, code to run, text to explain what you a producing and metadata to tell your software what kinds of outputs to generate from your markdown code. For more information on RMarkdown look <a href="https://rmarkdown.rstudio.com/">here</a>.</p></li>
<li><p>Git is a software version control system which allows you to keep track of the code you produce and the changes that you or others make to it.</p></li>
<li><p>GitHub is an online repository that allows anyone to view the code you have produced (in whatever language you choose to program in) and use/scrutinise/contribute to/comment on it.</p></li>
</ul>
<section id="setup" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">2.5.1</span> Setup</h3>
<ol type="1">
<li><p>First need to install Git — https://git-scm.com/</p></li>
<li><p>Go to http://github.com, create an account and create a new repository (call it anything you like - ‘gis_code’ or something similar), making sure it is public and you check the box that says ‘initialise new repository with a README’ — click ‘create repository’ at the bottom</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/github.png" class="img-fluid figure-img" style="width:9.72222in"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Your new repository (‘repo’) will be created and this is where you will be able to store your code online. You will notice that a README.md markdown file has also been created. This can be edited to tell people what they are likely to find in this repository.</li>
</ol>
</section>
<section id="using-rstudio-with-git" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="using-rstudio-with-git"><span class="header-section-number">2.5.2</span> Using RStudio with Git</h3>
<p>In summer 2021 GitHub changed it’s authentication process to a token based system as opposed to a password based system. David Keys provided an <a href="https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/">excellent overview with some videos that documented this change and how to now set things up, which i have adapted here</a></p>
<section id="check-git-is-installed" class="level4" data-number="2.5.2.1">
<h4 data-number="2.5.2.1" class="anchored" data-anchor-id="check-git-is-installed"><span class="header-section-number">2.5.2.1</span> Check Git is installed</h4>
<p>Next to the console window you will see a terminal tab, check Git is installed with <code>which git</code> then <code>git --version</code> you should get a message in response that says where your git installation is and the version you have.</p>
</section>
<section id="configure-your-git" class="level4" data-number="2.5.2.2">
<h4 data-number="2.5.2.2" class="anchored" data-anchor-id="configure-your-git"><span class="header-section-number">2.5.2.2</span> Configure your Git</h4>
<p>You need to tell Git who you are and your GitHub username. The easiest way is to use the <code>usethis</code> package, you will need to install and library it.</p>
<p>Then, in the console, type the function <code>edit_git_config()</code></p>
<p>A Git config will load and you need to change your name and email to match GitHub.</p>
<p>If this is empty use the following template and save the file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>[user]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    name <span class="ot">=</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    email <span class="ot">=</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    username <span class="ot">=</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="connect-git-to-github" class="level4" data-number="2.5.2.3">
<h4 data-number="2.5.2.3" class="anchored" data-anchor-id="connect-git-to-github"><span class="header-section-number">2.5.2.3</span> Connect Git to GitHub</h4>
<p>From GitHub you need to generate a personal access token. You can use the function <code>create_github_token()</code> from the <code>usethis</code> package or also through</p>
<ul>
<li>GitHub &gt; settings &gt; Developer settings &gt; personal access tokens &gt; generate new token.</li>
</ul>
<p>Use a descriptive name and consider saving the token - it won’t save on GitHub</p>
<p>The last step is to store this token in Git with the <code>gitcreds</code> package &gt; install and load it &gt; then use the function <code>gitcreds_set()</code> &gt; copy your token in.</p>
<p>There are many different ways to use Git, GitHub and R. I will focus to two here. Read the next two parts then decide which to use.</p>
</section>
</section>
<section id="way-1---starting-fresh" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="way-1---starting-fresh"><span class="header-section-number">2.5.3</span> Way 1 - starting fresh</h3>
<p>The first way assumes you are starting fresh - meaning you don’t have a project but you know you want to put your work online.</p>
<ol type="1">
<li><p>Under setup we made a repository on GitHub. Copy that URL.</p></li>
<li><p>Open RStudio &gt; File New Project &gt; Version Control &gt; Git</p></li>
<li><p>Copy in the repository URL and provide a project directory name…but it should populate when you paste in the URL</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/easyway.png" class="img-fluid figure-img" style="width:5.55556in"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="way-2---if-have-an-existing-project" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="way-2---if-have-an-existing-project"><span class="header-section-number">2.5.4</span> Way 2 - If have an existing project</h3>
<ol type="1">
<li><p>Open RStudio and your existing project (or make a new one…i will make one here). In RStudio Tools &gt; Global Options, under ‘Git/SVN’ check the box to allow version control and locate the folder on your computer where the git.exe file is located — if you have installed git then this should be automatically there. If you make a new project make sure you create a file (<code>.R</code> or <code>.Rmd</code> through File &gt; New File), add something to it, then save it (File &gt; Save As) into your project folder. When it saves it should appear in the bottom right Files window.</p></li>
<li><p>Next go Tools &gt; Project Options &gt; Git/SVN &gt; and select the version control system as Git. You should now see a git tab in the environment window of RStudio (top right) and the files also appear under the Git tab. It should look something like this….</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/makeafile.png" class="img-fluid figure-img" style="width:11.11111in"></p>
</figure>
</div>
</div>
</div>
<p>Now you will be able to use Git and GitHub as per the following instructions…</p>
</section>
<section id="commiting-to-git" class="level3" data-number="2.5.5">
<h3 data-number="2.5.5" class="anchored" data-anchor-id="commiting-to-git"><span class="header-section-number">2.5.5</span> Commiting to Git</h3>
<ol type="1">
<li><p>As well as saving (as you normally do with any file), which saves a copy to our local directory, we will also ‘commit’ or create a save point for our work on git.</p></li>
<li><p>To do this, you should click the ‘Git’ icon and up will pop a menu like the one below:</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/commit1.png" class="img-fluid figure-img" style="width:5.55556in"></p>
</figure>
</div>
</div>
</div>
<p>You can also click the Git tab that will have appeared in the top-right window of RStudio. Up will then pop another window that looks a little like the one below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/commit2.png" class="img-fluid figure-img" style="width:11.11111in"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>Stage the changes, add a commit message so you can monitor the changes you make, then click commit</p></li>
<li><p>Make some more changes to your file and save it. Click commit again then in the review changes box you will be able to see what has changed within your file. Add a commit message and click commit:</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/commit3.png" class="img-fluid figure-img" style="width:8.33333in"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="push-to-github" class="level3" data-number="2.5.6">
<h3 data-number="2.5.6" class="anchored" data-anchor-id="push-to-github"><span class="header-section-number">2.5.6</span> Push to Github</h3>
<p>We need to create a new GitHub repo for our local project. Luckily the <code>usethis</code> package can do this for us. Simply type the function <code>use_github()</code> in the console and a new GitHub repo will appear using the name of your project!</p>
<p>Now we can push our changes to GitHub using the up arrow either in the RStudio Git tab (environment quadrant), or from the review changes box (opens when you click commit).</p>
<p>But….if the push button is greyed out go to the section [Greyed out push button]</p>
</section>
<section id="pull-from-github" class="level3" data-number="2.5.7">
<h3 data-number="2.5.7" class="anchored" data-anchor-id="pull-from-github"><span class="header-section-number">2.5.7</span> Pull from GitHub</h3>
<ol type="1">
<li><p>Pull will take any changes to the global repo and bring them into your local repo. Go to your example GitHub repo (online) and click on your test file &gt; edit this file.</p></li>
<li><p>Add a line of code or a comment, preview the changes then commit directly to the main branch.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/pullexample.png" class="img-fluid figure-img" style="width:11.11111in"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Now in RStudio click the down arrow (Pull) request. Your file should update in RStudio.</li>
</ol>
<p>If you were to update your file on GitHub and your local one in RStudio separately you would receive an error message in RStudio when you attempted to commit.</p>
<p>If you’d rather use terminal to control Git then you can. If you have a large project RStudio sometimes has limits on file name length (e.g.&nbsp;this might occur with a book, like this one). To get around this you can use the following commands:</p>
<ul>
<li><code>git add .</code> to stage all files</li>
<li><code>git commit -m "commit comment"</code> to commit all the staged files</li>
<li><code>git push</code> to push the committed files to the remote</li>
</ul>
<p><strong>Now take the code you have used this week and put it on GitHub and add the link to the shared spreadsheet</strong></p>
<p><strong>However</strong> note that GitHub has a maximum file size of 50mb, if you have larger files you must ignore them in the <code>.gitignore</code> file…e.g.&nbsp;my .gitignore looks like this..</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>prac1_data<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>prac2_data<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>prac3_data<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>prac4_data<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>prac1_images<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>prac2_images<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>prac3_images<span class="sc">/</span><span class="er">*</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>prac4_images<span class="sc">/</span><span class="er">*</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="forking" class="level3" data-number="2.5.8">
<h3 data-number="2.5.8" class="anchored" data-anchor-id="forking"><span class="header-section-number">2.5.8</span> Forking</h3>
<p>A Fork in GitHub is a copy of someone’s repository to your own GitHub account. You could use it as a base starting point for your project or to make a fix and then submit a <em>pull</em> request to the original owner who would then pull your changes to their repository.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Your homework task is to:</p>
<ul>
<li>select a GitHub respoitoiry from the shared spreadsheet</li>
<li>click fork (on GitHub)</li>
<li>clone the repository into a new Rproject (as per way 1 above)</li>
<li>make a map of the malaria death rate</li>
<li>push to GitHub</li>
<li>submit a pull request to the original owner (otherwise know as the original upstream repository)…</li>
</ul>
<p>the pull request will look something like this…</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac2_images/pull.jpg" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Pull request. Source: <a href="https://codex.so/fork-and-pull-en">codex (2024)</a></figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>Git and GitHub have many more features that we haven’t covered today. This is because when we are working on our own on a small project we hopefully won’t need them.</p>
<p>For more information on these features - such as going back in time from Git or GitHub see <a href="https://andrewmaclachlan.github.io/CASA0005repo/extra-reproducibility.html#git-and-github-1">my other resources</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01_geographic_data.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Geographic information</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_point_patterns.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Point patterns and autocorrelation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>